//EIBDRMFC JOB MSGCLASS=X,MSGLEVEL=(1,1),REGION=8M                      JOB33290
/*JOBPARM S=S1M1
//*-------------------------------------------------------------------*
//* PROGRAM  : EIBDRMFC
//* DESC     : GENERATE A DAILY REPORT SEGREGATED INTO RINGGIT AND
//*            FOREIGN CURRENCY DEPOSIT
//* ESMR     : 2010-3059 (AAB)
//*-------------------------------------------------------------------*
//DELETE  EXEC PGM=IEFBR14
//DEL01   DD DSN=SAP.PBB.MNI.FDRMFC,
//           DISP=(MOD,DELETE,DELETE),
//           SPACE=(CYL,(0))
//*-------------------------------------------------------------------*
//EIBDRMFC  EXEC SAS609
//MNIFD     DD DSN=SAP.PBB.MNIFD.DAILY(0),DISP=SHR
//SASLIST   DD DSN=SAP.PBB.MNI.FDRMFC,
//             DISP=(NEW,CATLG,DELETE),
//             SPACE=(CYL,(3,2),RLSE),UNIT=SYSDA,
//             DCB=(RECFM=FB,LRECL=150,BLKSIZE=0,DSORG=PS)
//SYSIN     DD *

OPTIONS YEARCUTOFF=1950 NOCENTER NODATE NONUMBER;

DATA REPTDATE;
   SET MNIFD.REPTDATE;
   CALL SYMPUT('RDATE',PUT(REPTDATE, DDMMYY8.));
   CALL SYMPUT('SDATE',PUT(REPTDATE, 8.));
RUN;

DATA FD;
   SET MNIFD.FD;
   KEEP CURCODE CURBAL FORATE MATDATE TENOR RATE AMTENOR AMTENORATE
        REPTDATE;
   WHERE CURBAL GT 0;

   IF CURCODE NE 'MYR' THEN
      CURBAL  = CURBAL/FORATE;

   IF MATDATE NOT IN (0,.) THEN DO;
      DD = SUBSTR(PUT(MATDATE,Z8.),7,2);
      MM = SUBSTR(PUT(MATDATE,Z8.),5,2);
      YY = SUBSTR(PUT(MATDATE,Z8.),1,4);
      MATDATE = MDY(MM,DD,YY);
   END;

   REPTDATE   = "&SDATE";
   TENOR      = MATDATE-REPTDATE;
   AMTENOR    = CURBAL*TENOR;
   AMTENORATE = AMTENOR*RATE;

   IF MATDATE EQ REPTDATE THEN
      DELETE;
RUN;

PROC SORT DATA=FD OUT=FD;
   BY CURCODE;
RUN;

PROC SUMMARY DATA=FD NWAY;
   CLASS  CURCODE;
   VAR    CURBAL AMTENOR AMTENORATE;
   OUTPUT OUT=ALLFD (DROP= _TYPE_ RENAME=_FREQ_=NOACCT)
          SUM=CURBAL AMTENOR AMTENORATE;
RUN;

DATA FD;
   SET ALLFD;
   AVGTENOR = AMTENOR/CURBAL;
   AVGRATE  = AMTENORATE/AMTENOR;
RUN;
   TITLE1 'REPORT ID : EIBDRMFC';
   TITLE2 'OUTSTANDING CUSTOMERS FCY FIXED DEPOSIT PLACEMENTS '
          '(FOR INDIVIDUALS AND CORPORATES)';
   TITLE3 'AS AT ' "&RDATE";
RUN;
 DATA _NULL_;
 SET FD;
 FILE SASLIST;
   IF _N_ = 1 THEN DO;
       PUT @001 'REPORT ID : EIBDRMFC';
       PUT @001 'OUTSTANDING CUSTOMERS FCY FIXED DEPOSIT PLACEMENTS';
       PUT @001 '(FOR INDIVIDUALS AND CORPORATES) AS AT ' "&RDATE";
       PUT @001 ;
       PUT @001 'CURRENCY CODE'
           @025 ',OUTSTANDING BALANCE'
           @050 ',AVERAGE TENOR (DAYS)'
           @075 ',AVERAGE RATE (%)'
           @100 ',NO OF O/S ACCOUNT';
   END;
   PUT @001 CURCODE
       @025 ',' CURBAL 20.2
       @050 ',' AVGTENOR 16.
       @075 ',' AVGRATE 16.2
       @100 ',' NOACCT 16.
       ;
   RUN;
