/************************************************************/
/** PROGRAM : PBBELQ (SPLIT FROM PBBELP)                   **/
/** MACRO TO PRINT THE DETAIL DAILY EL ITEMS               **/
/** FOR DAY A - DAY H                                      **/
/************************************************************/
%INC PGM(PBBELF);

%MACRO PRTEL(I);

PROC DATASETS LIB=WORK NOLIST;
  DELETE ELW;
RUN;
*;
DATA ELG;
  SET ELG.GOLD&REPTMON&NOWK;
  IF  ELDAY="&I";
*;
DATA PMM;
  SET BNMK.TBL1&REPTMON&NOWK
      BNMK.DCI&REPTMON&NOWK(DROP=REPTDATS);
  IF  ELDAY="&I";
*;
DATA REP6;
   SET REP2 REP4;
   IF  BNMCODE='3250000000000Y' THEN AMOUNT=NETAMT;
   BNMCODE='4017100000000Y';
   IF ELDAY="&I";

DATA ELW1;
  SET BNM.ELW&REPTMON&NOWK;
  AMOUNT=ABS(AMOUNT);

  IF  BNMCODE='4929980000000Y' AND BRANCH > 3000 THEN DELETE;

  IF  BNMCODE IN ('3219902000000Y','3219903000000Y','3219912000000Y')
      THEN DO;
      BNMCODE='3219910000000Y'; OUTPUT;
  END;
  ELSE
  IF  BNMCODE IN ('4411100000000Y','4414000000000Y',
                  '4413000000000Y') THEN DO;
      BNXCODE=BNMCODE;
      IF BNXCODE='4411100000000Y' THEN BNMCODE='4411100000000Y';
      IF BNXCODE='4414000000000Y' THEN BNMCODE='4414000000000Y';
      IF BNXCODE^='4413000000000Y' THEN OUTPUT;
      BNMCODE='4410000000000Y';
      OUTPUT;
  END;
  ELSE
  IF  BNMCODE='4019000000000Y' THEN DO;
      BNMCODE='4019100000000Y'; OUTPUT;
      BNMCODE='4019000000000Y';
      AMOUNT=0.00; OUTPUT;
  END;
  ELSE OUTPUT;
*;
PROC SORT DATA=ELW1 (WHERE=(ELDAY="&I"))
          OUT=ELW (KEEP=BNMCODE AMOUNT);
BY BNMCODE;
RUN;
*;
DATA ELW;
  SET ELW REP6 PMM ELG;
*;
PROC SUMMARY DATA=ELW NWAY;
CLASS BNMCODE; VAR AMOUNT;
OUTPUT OUT=ELW (DROP=_TYPE_ _FREQ_) SUM=;
PROC SORT DATA=EL (DROP=TYPE)
          OUT=ELITEM;
BY BNMCODE;
RUN;

DATA ELW;
  FORMAT FMTNAME $7.;
  MERGE ELW (IN=A)
        ELITEM (IN=B);
  BY BNMCODE;
  IF B;
  IF NOT A THEN AMOUNT=0.00;
  TOTAL=AMOUNT;

  IF IDX NE ' ';
  FMTNAME=IDX||'-'||FMTNAME;

  IF  BNMCODE='4314017000000Y' THEN DO;
      DESC='O/W RM IBB FROM CAGAMAS '||PUT(AMOUNT,COMMA14.2);
      AMOUNT=0.00; TOTAL=0.00;
  END;

  AMOUNX=AMOUNT;
  TOTALX=TOTAL;

  IF SIGN='-' THEN DO;
     AMOUNX=(-1)*AMOUNT; TOTALX=AMOUNX;
  END;


  IF BNMCODE='4017100000000Y'
     THEN DESC='TOTAL RM MARKETABLE SECURITIES';
  IF BNMCODE='4019000000000Y' THEN DELETE;
  IF BNMCODE='4019100000000Y' THEN DELETE;
RUN;
*;
DATA ELWT;
  SET ELW;
  BNMCODE='4013000000000Y';
  FMTNAME='E-ELSRR';
  SIGN   ='+';
  DESC   ='ELIGIBLE LIABILITIES FOR SRR NEXT MONTH';

  IF IDX IN ('B','D') THEN DO;
      AMOUNX=(-1)*AMOUNT; TOTALX=AMOUNX;
  END;
*;
PROC SUMMARY DATA=ELWT NWAY;
CLASS BNMCODE FMTNAME DESC SIGN;
VAR   AMOUNT TOTAL AMOUNX TOTALX;
OUTPUT OUT=ELWT (DROP=_TYPE_ _FREQ_) SUM=;
*;
DATA ELWT;
  SET ELWT;
  AMOUNT=AMOUNX; TOTAL=TOTALX;
*;
DATA ELW;
  SET ELWT ELW;
*;
PROC SORT DATA=ELW; BY FMTNAME SIGN BNMCODE; RUN;
*;
OPTIONS NONUMBER NODATE NOCENTER;
TITLE1 &SDESC;
TITLE2 'DETAIL TOTAL ELIGIBLE LIABILITIES ITEMS FOR : ' &I;
TITLE3 'REPORT DATE : ' &RDATE;
TITLE4;
*;
PROC   REPORT DATA=ELW NOWD HEADLINE SPLIT='*';
WHERE  FMTNAME IN ('A-RMEL','B-RMEA');
COLUMN FMTNAME BNMCODE DESC SIGN AMOUNT TOTAL AMOUNX TOTALX;
DEFINE FMTNAME  / GROUP   FORMAT=$7.;
DEFINE BNMCODE  /         FORMAT=$14.;
DEFINE DESC     /         FORMAT=$40.;
DEFINE SIGN     /         FORMAT=$4.       'SIGN';
DEFINE AMOUNT   / SUM     FORMAT=COMMA22.2 'AMOUNT';
DEFINE TOTAL    / SUM     FORMAT=COMMA22.2 'TOTAL ';
DEFINE AMOUNX   / SUM     NOPRINT;
DEFINE TOTALX   / SUM     NOPRINT;
BREAK   AFTER FMTNAME /;
COMPUTE AFTER FMTNAME;
LINE @003 119*'-';
LINE @012 'TOTAL FOR ' FMTNAME $7.
     @074 AMOUNX.SUM  COMMA24.2
     @098 TOTALX.SUM   COMMA24.2;
LINE @074 24*'-' @098 24*'-';
ENDCOMP;
RUN;
*;
PROC   REPORT DATA=ELW NOWD SPLIT='*';
WHERE  FMTNAME NOT IN ('A-RMEL','B-RMEA');
COLUMN FMTNAME BNMCODE DESC SIGN AMOUNT TOTAL;
DEFINE FMTNAME  /         FORMAT=$7.    '     ';
DEFINE BNMCODE  /         FORMAT=$14.   '     ';
DEFINE DESC     /         FORMAT=$40.   '     ';
DEFINE SIGN     /         FORMAT=$4.    '     ';
DEFINE AMOUNT   /         FORMAT=COMMA22.2 '      ';
DEFINE TOTAL    /         FORMAT=COMMA22.2 '      ';
%MEND;
*;
%PRTEL(DAYA);
%PRTEL(DAYB);
%PRTEL(DAYC);
%PRTEL(DAYD);
%PRTEL(DAYE);
%PRTEL(DAYF);
%PRTEL(DAYG);
%PRTEL(DAYH);

%MACRO PRTELI(I);
PROC DATASETS LIB=WORK NOLIST;
  DELETE ELW;
RUN;
*;
DATA REP7;
   SET REP2 REP4;
   IF  BNMCODE='3250000000000Y' THEN AMOUNT=NETAMT;
   BNMCODE='4017100000000Y';
   IF ELDAY="&I";
*;
PROC SUMMARY DATA=REP7 NWAY;
CLASS BNMCODE; VAR AMOUNT;
OUTPUT OUT=REP7 (DROP=_TYPE_ _FREQ_) SUM=;
*;
PROC SORT DATA=ELW1 (WHERE=(ELDAY="&I"))
          OUT=ELW (KEEP=BNMCODE AMOUNT);
BY BNMCODE;
RUN;
*;
DATA PMM;
  SET BNMK.DCI&REPTMON&NOWK(DROP=REPTDATS)
      BNMK.TBL1&REPTMON&NOWK;
  IF  ELDAY="&I";
*;
DATA ELG;
  SET ELG.GOLD&REPTMON&NOWK;
  IF  ELDAY="&I";
*;
DATA ELW;
  SET ELW REP7 PMM ELG;
RUN;
PROC SUMMARY DATA=ELW NWAY;
CLASS BNMCODE; VAR AMOUNT;
OUTPUT OUT=ELW (DROP=_TYPE_ _FREQ_) SUM=;
*;
PROC SORT DATA=ELI (DROP=TYPE)
          OUT=ELITEM;
BY BNMCODE;
RUN;

DATA ELW;
  FORMAT FMTNAME $7.;
  MERGE ELW (IN=A)
        ELITEM (IN=B);
  BY BNMCODE;
  IF B;
  IF NOT A THEN AMOUNT=0.00;
  TOTAL=AMOUNT;

  IF IDX NE ' ';
  FMTNAME=IDX||'-'||FMTNAME;

  IF  BNMCODE='4314017000000Y' THEN DO;
      DESC='O/W RM IBB FROM CAGAMAS '||PUT(AMOUNT,COMMA14.2);
      AMOUNT=0.00; TOTAL=0.00;
  END;

  AMOUNX=AMOUNT;
  TOTALX=TOTAL;

  IF SIGN='-' THEN DO;
     AMOUNX=(-1)*AMOUNT; TOTALX=AMOUNX;
  END;

  IF BNMCODE='4017100000000Y'
     THEN DESC='TOTAL RM MARKETABLE SECURITIES';

  WK='4';
  IF WK NE "&NOWK" THEN DO;
     IF BNMCODE = '4019000000000Y' THEN DELETE;
     IF BNMCODE = '4019100000000Y' THEN DELETE;
  END;

RUN;
*;
DATA ELWT;
  SET ELW;
  BNMCODE='4013000000000Y';
  FMTNAME='E-ELSRR';
  SIGN   ='+';
  DESC   ='ELIGIBLE LIABILITIES FOR SRR NEXT MONTH';

  IF IDX IN ('B','D') THEN DO;
      AMOUNX=(-1)*AMOUNT; TOTALX=AMOUNX;
  END;
*;
PROC SUMMARY DATA=ELWT NWAY;
CLASS BNMCODE FMTNAME DESC SIGN;
VAR   AMOUNT TOTAL AMOUNX TOTALX;
OUTPUT OUT=ELWT (DROP=_TYPE_ _FREQ_) SUM=;
*;
DATA ELWT;
  SET ELWT;
  AMOUNT=AMOUNX; TOTAL=TOTALX;
*;
DATA ELW;
  SET ELWT ELW;
*;
PROC SORT DATA=ELW; BY FMTNAME SIGN BNMCODE; RUN;
*;
OPTIONS NONUMBER NODATE NOCENTER;
TITLE1 'DETAIL TOTAL ELIGIBLE LIABILITIES ITEMS FOR : ' &I;
TITLE2 'REPORT DATE : ' &RDATE;
TITLE3;
*;
PROC   REPORT DATA=ELW NOWD HEADLINE SPLIT='*';
WHERE  FMTNAME IN ('A-RMEL','B-RMEA');
COLUMN FMTNAME BNMCODE DESC SIGN AMOUNT TOTAL AMOUNX TOTALX;
DEFINE FMTNAME  / GROUP   FORMAT=$7.;
DEFINE BNMCODE  /         FORMAT=$14.;
DEFINE DESC     /         FORMAT=$40.;
DEFINE SIGN     /         FORMAT=$4.       'SIGN';
DEFINE AMOUNT   / SUM     FORMAT=COMMA22.2 'AMOUNT';
DEFINE TOTAL    / SUM     FORMAT=COMMA22.2 'TOTAL ';
DEFINE AMOUNX   / SUM     NOPRINT;
DEFINE TOTALX   / SUM     NOPRINT;
BREAK   AFTER FMTNAME /;
COMPUTE AFTER FMTNAME;
LINE @003 119*'-';
LINE @012 'TOTAL FOR ' FMTNAME $7.
     @074 AMOUNX.SUM  COMMA24.2
     @098 TOTALX.SUM   COMMA24.2;
LINE @074 24*'-' @098 24*'-';
ENDCOMP;
RUN;
*;
PROC   REPORT DATA=ELW NOWD SPLIT='*';
WHERE  FMTNAME NOT IN ('A-RMEL','B-RMEA');
COLUMN FMTNAME BNMCODE DESC SIGN AMOUNT TOTAL;
DEFINE FMTNAME  /         FORMAT=$7.    '     ';
DEFINE BNMCODE  /         FORMAT=$14.   '     ';
DEFINE DESC     /         FORMAT=$40.   '     ';
DEFINE SIGN     /         FORMAT=$4.    '     ';
DEFINE AMOUNT   /         FORMAT=COMMA22.2 '      ';
DEFINE TOTAL    /         FORMAT=COMMA22.2 '      ';
RUN;
%MEND;
%PRTELI(DAYI);
*;
