#!/usr/bin/env python3
"""
Program : ARTBFMT.py
Purpose : Data definition (format library) for Amanah Raya report.
          Provides Python equivalents of SAS PROC FORMAT value lists:
            - $FUNDMNE : fund name (no-space) -> fund mnemonic code
            - FUNDTYPE : numeric fund-type code -> description
          Also provides PMFUND, the equivalent of the SAS macro variable
          %LET PMFUND=(...) used elsewhere (e.g. in WHERE / IN clauses)
          to filter Public Mutual fund names.
"""

# ============================================================================
# DATA DEFINITION FOR AMANAH RAYA REPORT
# ============================================================================

# ----------------------------------------------------------------------------
# VALUE $FUNDMNE     /* FUND MNEMONIC LISTING */
# Keys below are the no-space fund names exactly as coded in the SAS format;
# lookup falls back to ' ' when the key is not found (SAS OTHER = ' ').
# ----------------------------------------------------------------------------
FUNDMNE_MAP = {
    "ARTB-PBFIXEDINCOMEFUND": "ARBPFI",
    "ARTB-PUBLICEQUITYFUND": "ARBPEF",
    "ARTB-PUBLICGROWTHFUND": "ARBPGF",
    "ARTB-PUBLICISLAMICDIVIDENDFUND": "ARBPID",
    "ARTB-PISLAMICASIATACTICALALLOCATION": "ARBABF",
    "ARTB-PBASIAEMERGINGGROWTHFUND": "ARTAEG",
    "ARTB-PBASIAEQUITYFUND": "ARBPAE",
    "ARTB-PBASIAPACIFICENTERPRISESFUND": "ARTPAP",
    "ARTB-PBASIAREALESTATEINCOMEFUND": "ARBARE",
    "ARTB-PBAUSTRALIADYNAMICBALANCEDFUND": "ARTPAD",
    "ARTB-PBBALANCEDFUND": "ARBPBF",
    "ARTB-PBBONDFUND": "ARTPBD",
    "ARTB-PBCASHMANAGEMENTFUND": "ARBPCM",
    "ARTB-PBCASHPLUSFUND": "ARBCPF",
    "ARTB-PBCHINAASEANEQUITYFUND": "ARTCAE",
    "ARTB-PBCHINAAUSTRALIAEQUITYFUND": "ARTCAF",
    "ARTB-PBCHINAPACIFICEQUITYFUND": "ARBPCP",
    "ARTB-PBCAPITALPROTECTEDDRAGONFUND": "ARTCPD",
    "ARTB-PBGROWTHFUND": "ARBPBG",
    "ARTB-PBGROWTHSEQUELFUND": "ARTPGS",
    "ARTB-PBINDONESIABALANCEDFUND": "ARTNDB",
    "ARTB-PBINFRASTRUCTUREBONDFUND": "ARTPIB",
    "ARTB-PBISLAMICASIAEQUITYFUND": "ARBPBA",
    "ARTB-PBISLAMICASIASTRATEGICSECTOR": "ARBSSF",
    "ARTB-PBISLAMICBONDFUND": "ARBIEF",
    "ARTB-PBISLAMICCASHPLUSFUND": "ARTCPF",
    "ARTB-PBISLAMICEQUITYFUND": "ARBPBI",
    "ARTB-PBSINGAPOREADVANTAGE-30EQUITY": "ARTS30",
    "ARTB-PBSUKUKFUND": "ARTPSD",
    "ARTB-PBBMTNFUND1": "ARTPM1",
    "ARTB-PUBLICASIAITTIKALFUND": "ARBAIF",
    "ARTB-PUBLICAUSTRALIAEQUITYFUND": "ARTPAE",
    "ARTB-PUBLICCHINAITTIKALFUND": "ARBPCF",
    "ARTB-PUBLICCHINASELECTFUND": "ARBCSF",
    "ARTB-PUBLICCHINATITANSFUND": "ARTPCT",
    "ARTB-PUBLICDIVIDENDSELECTFUND": "ARBPDS",
    "ARTB-PUBLICENHANCEDBONDFUND": "ARBPEB",
    "ARTB-PUBLICENTERPRISESBONDFUND": "ARTETB",
    "ARTB-PUBLICFAR-EASTALPHA-30FUND": "ARTP30",
    "ARTB-PUBLICFAR-EASTTELCO&": "ARBTEL",
    "ARTB-PUBLICFAR-EASTBALANCEDFUND": "ARBPFB",
    "ARTB-PUBLICFAR-EASTCONSUMERTHEMESF": "ARBCTF",
    "ARTB-PUBLICFAR-EASTDIVIDENDFUND": "ARBPFD",
    "ARTB-PUBLICFAR-EASTPROPERTY&RESORTS": "ARBPRF",
    "ARTB-PUBLICFAR-EASTSELECTFUND": "ARBPFE",
    "ARTB-PUBLICGLOBALSELECTFUND": "ARBGSF",
    "ARTB-PUBLICINDEXFUND": "ARBPIF",
    "ARTB-PUBLICINDONESIASELECTFUND": "ARTPIF",
    "ARTB-PUBLICINSTITUTIONALBONDFUND": "ARBPIB",
    "ARTB-PUBLICISLAMICALPHA-40GROWTH": "ARTI40",
    "ARTB-PUBLICISLAMICASIADIVIDENDFUND": "ARBIAD",
    "ARTB-PUBLICISLAMICASIALEADERSEQUITY": "ARTPIA",
    "ARTB-PUBLICISLAMICBONDFUND": "ARBPIS",
    "ARTB-PUBLICISLAMICENHANCEDBONDFUND": "ARBPCI",
    "ARTB-PUBLICISLAMICEQUITYFUND": "ARBPIE",
    "ARTB-PUBLICISLAMICINCOMEFUND": "ARTPII",
    "ARTB-PUBLICISLAMICINFRASTRUCTUREBOND": "ARTIIB",
    "ARTB-PUBLICISLAMICMIXEDASSETFUND": "ARBIBF",
    "ARTB-PUBLICISLAMICMONEYMARKETFUND": "ARBIMM",
    "ARTB-PUBLICISLAMICOPPORTUNITIESFUND": "ARBPIO",
    "ARTB-PUBLICISLAMICOPTIMALGROWTHFUND": "ARBIOG",
    "ARTB-PUBLICISLAMICSAVINGSFUND": "ARTPSI",
    "ARTB-PUBLICISLAMICSECTORSELECTFUND": "ARBISS",
    "ARTB-PUBLICISLAMICSELECTBONDFUND": "ARBISB",
    "ARTB-PUBLICISLAMICSELECTENTERPRISES": "ARTPIS",
    "ARTB-PUBLICISLAMICSELECTTREASURES": "ARTIST",
    "ARTB-PUBLICISLAMICSTRATEGICBONDFUND": "ARTPBS",
    "ARTB-PUBLICISLAMICTREASURESGROWTH": "ARTPIT",
    "ARTB-PUBLICITTIKALSEQUELFUND": "ARTISQ",
    "ARTB-PUBLICNATURALRESOURCESEQUITY": "ARTNRE",
    "ARTB-PUBLICOPTIMALGROWTHFUND": "ARTOGF",
    "ARTB-PUBLICSAVINGSFUND": "ARBPSF",
    "ARTB-PUBLICSECTORSELECTFUND": "ARBPSS",
    "ARTB-PUBLICSELECTALPHA-30FUND": "ARTPSA",
    "ARTB-PUBLICSELECTBONDFUND": "ARBPSB",
    "ARTB-PUBLICSINGAPOREEQUITYFUND": "ARTSEF",
    "ARTB-PUBLICSMALLCAPFUND": "ARBPSC",
    "ARTB-PUBLICSOUTH-EASTASIASELECTFUND": "ARBPSE",
    "ARTB-PUBLICSTRATEGICBONDFUND": "ARTSTR",
    "ARTB-PUBLICSTRATEGICSMALLCAPFUND": "ARTSSC",
    "ARTB-PUBLICSUKUKFUND": "ARTPSK",
    "ARTB-PUBLICTACTICALALLOCATIONFUND": "ARBPGB",
    "ARTB-PUBLICFAREAST-APLHA-30FUND": "ARTP30",
    "ARTB-PUBLICCAPITALPROTECTEDSELECT": "ARTPCP",
    "ARTB-PBCAPITALPROTECTEDRESOURCESFUND": "ARTPCR",
}

FUNDMNE_OTHER_DEFAULT = " "  # OTHER = ' '


def get_fundmne(value: str) -> str:
    """Equivalent of PUT(value, $FUNDMNE.) — returns mnemonic or ' ' (OTHER)."""
    return FUNDMNE_MAP.get(value, FUNDMNE_OTHER_DEFAULT)


# ----------------------------------------------------------------------------
# VALUE FUNDTYPE
# ----------------------------------------------------------------------------
FUNDTYPE_MAP = {
    1: "PUBLIC MUTUAL FUND",
    2: "NON-PUBLIC MUTUAL FUND",
}


def get_fundtype(value: int):
    """Equivalent of PUT(value, FUNDTYPE.). Returns None if value not mapped."""
    return FUNDTYPE_MAP.get(value)


# ----------------------------------------------------------------------------
# %LET PMFUND =( ... )
# Equivalent of the SAS macro variable holding the Public Mutual fund name
# list (used elsewhere as an IN-clause filter, e.g. WHERE FUNDNAME IN PMFUND).
# Kept as a tuple of literal strings, exactly as coded in the SAS macro
# (including embedded quotes/apostrophes and spacing).
# ----------------------------------------------------------------------------
PMFUND = (
    "ARTB-PB FIXED INCOME FUND",
    "ARTB-PUBLIC EQUITY FUND",
    "ARTB-PUBLIC GROWTH FUND",
    "ARTB-PUBLIC ISLAMIC DIVIDEND FUND",
    "ARTB-P ISLAMIC ASIA TACTICAL ALLOCATION",
    "ARTB-PB ASIA EMERGING GROWTH FUND",
    "ARTB-PB ASIA EQUITY FUND",
    "ARTB-PB ASIA PACIFIC ENTERPRISES FUND",
    "ARTB-PB ASIA REAL ESTATE INCOME FUND",
    "ARTB-PB AUSTRALIA DYNAMIC BALANCED FUND",
    "ARTB-PB BALANCED FUND",
    "ARTB-PB BOND FUND",
    "ARTB-PB CASH MANAGEMENT FUND",
    "ARTB-PB CASH PLUS FUND",
    "ARTB-PB CHINA ASEAN EQUITY FUND",
    "ARTB-PB CHINA AUSTRALIA EQUITY FUND",
    "ARTB-PB CHINA PACIFIC EQUITY FUND",
    "ARTB-PB GROWTH FUND",
    "ARTB-PB GROWTH SEQUEL FUND",
    "ARTB-PB INDONESIA BALANCED FUND",
    "ARTB-PB INFRASTRUCTURE BOND FUND",
    "ARTB-PB ISLAMIC ASIA EQUITY FUND",
    "ARTB-PB ISLAMIC ASIA STRATEGIC SECTOR",
    "ARTB-PB ISLAMIC BOND FUND",
    "ARTB-PB ISLAMIC CASH PLUS FUND",
    "ARTB-PB ISLAMIC EQUITY FUND",
    "ARTB-PB SINGAPORE ADVANTAGE-30 EQUITY",
    "ARTB-PB SUKUK FUND",
    "ARTB-PBB MTN FUND 1",
    "ARTB-PUBLIC ASIA ITTIKAL FUND",
    "ARTB-PUBLIC AUSTRALIA EQUITY FUND",
    "ARTB-PUBLIC CHINA ITTIKAL FUND",
    "ARTB-PUBLIC CHINA SELECT FUND",
    "ARTB-PUBLIC CHINA TITAN FUND",
    "ARTB-PUBLIC DIVIDEND SELECT FUND",
    "ARTB-PUBLIC ENHANCED BOND FUND",
    "ARTB-PUBLIC ENTERPRISES BOND FUND",
    "ARTB-PUBLIC FAR-EAST ALPHA-30 FUND",
    "ARTB-PUBLIC FAR-EAST TELCO &",
    "ARTB-PUBLIC FAR-EAST BALANCED FUND",
    "ARTB-PUBLIC FAR-EAST CONSUMER THEMES F",
    "ARTB-PUBLIC FAR-EAST DIVIDEND FUND",
    "ARTB-PUBLIC FAR-EAST PROPERTY & RESORTS",
    "ARTB-PUBLIC FAR-EAST SELECT FUND",
    "ARTB-PUBLIC GLOBAL SELECT FUND",
    "ARTB-PUBLIC INDEX FUND",
    "ARTB-PUBLIC INDONESIA SELECT FUND",
    "ARTB-PUBLIC INSTITUTIONAL BOND FUND",
    "ARTB-PUBLIC ISLAMIC ALPHA-40 GROWTH",
    "ARTB-PUBLIC ISLAMIC ASIA DIVIDEND FUND",
    "ARTB-PUBLIC ISLAMIC ASIA LEADERS EQUITY",
    "ARTB-PUBLIC ISLAMIC BOND FUND",
    "ARTB-PUBLIC ISLAMIC ENHANCED BOND FUND",
    "ARTB-PUBLIC ISLAMIC EQUITY FUND",
    "ARTB-PUBLIC ISLAMIC INCOME FUND",
    "ARTB-PUBLIC ISLAMIC INFRASTRUCTURE BOND",
    "ARTB-PUBLIC ISLAMIC MIXED ASSET FUND",
    "ARTB-PUBLIC ISLAMIC MONEY MARKET FUND",
    "ARTB-PUBLIC ISLAMIC OPPORTUNITIES FUND",
    "ARTB-PUBLIC ISLAMIC OPTIMAL GROWTH FUND",
    "ARTB-PUBLIC ISLAMIC SAVINGS FUND",
    "ARTB-PUBLIC ISLAMIC SECTOR SELECT FUND",
    "ARTB-PUBLIC ISLAMIC SELECT BOND FUND",
    "ARTB-PUBLIC ISLAMIC SELECT ENTERPRISES",
    "ARTB-PUBLIC ISLAMIC SELECT TREASURES",
    "ARTB-PUBLIC ISLAMIC STRATEGIC BOND FUND",
    "ARTB-PUBLIC ISLAMIC TREASURES GROWTH",
    "ARTB-PUBLIC ITTIKAL SEQUEL FUND",
    "ARTB-PUBLIC NATURAL RESOURCES EQUITY",
    "ARTB-PUBLIC OPTIMAL GROWTH FUND",
    "ARTB-PUBLIC SAVINGS FUND",
    "ARTB-PUBLIC SECTOR SELECT FUND",
    "ARTB-PUBLIC SELECT ALPHA-30 FUND",
    "ARTB-PUBLIC SELECT BOND FUND",
    "ARTB-PUBLIC SINGAPORE EQUITY FUND",
    "ARTB-PUBLIC SMALLCAP FUND",
    "ARTB-PUBLIC SOUTH-EAST ASIA SELECT FUND",
    "ARTB-PUBLIC STRATEGIC BOND FUND",
    "ARTB-PUBLIC STRATEGIC SMALLCAP FUND",
    "ARTB-PUBLIC SUKUK FUND",
    "ARTB-PUBLIC TACTICAL ALLOCATION FUND",
    "AMANAHRAYA TRUSTEES BERHAD-PUBLIC",
    "ARTB-PUBLIC MUTUAL BERHAD'S FUNDS",
    "AMANAHRAYA TRUSTEES BHD-PUBLIC ASIA",
    "AMANAHRAYA TRUSTEES BERHAD-PB ISLAMIC",
    "ARTB-PUBLIC ISLAMIC ASIA TACTICAL",
    "ARTB-PUBLIC GROWTH FUND",
    "ARTB-PUBLIC FAR EAST-APLHA-30 FUND",
    "ARTB-PB MIXED ASSET CONSERVATIVE FUND",
    "ARTB-PB DYNAMIC ALLOCATION FUND",
    "ARTB-PB ASIA EQUITY FUND",
    "ARTB-PUBLIC EQUITY FUND",
    "AMANAH RAYA BHD-PUBLIC EQUITY FUND",
    "AMANAHRAYA TRUSTEE BHD-PB ISLAMIC EQUITY",
    "AMANAHRAYA TRUSTEES BERHAD - PUBLIC",
    "AMANAHRAYA TRUSTEES BERHAD-PB ASIA",
    "AMANAHRAYA TRUSTEES BERHAD-PB BOND FUND",
    "AMANAHRAYA TRUSTEES BERHAD-PB INDONESIA",
    "AMANAHRAYA TRUSTEES BERHAD-PBB MTN FUND1",
    "AMANAHRAYA TRUSTEES BERHAD-PUBLIC GLOBAL",
    "AMANAHRAYA TRUSTEES BERHAD-PUBLIC SELECT",
    "AMANAHRAYA TRUSTEES BHD-PB CASH MGT FUND",
    "AMANAHRAYA TRUSTEES BHD-PB GROWTH FUND",
    "AMANAHRAYA TRUSTEES BHD-PUBLIC SAVINGS",
    "ARTB-PUBLIC MUTUAL PRS ISLAMIC",
    "ARTB-PUBLIC MUTUAL PRS ISLAMIC MODERATE",
    "ARTB-PUBLIC MUTUAL PRS ISLAMIC GROWTH",
    "ARTB-PUBLIC MUTUAL PRS CONSERVATIVE FUND",
    "ARTB-PUBLIC MUTUAL PRS GROWTH FUND",
    "ARTB-PUBLIC MUTUAL PRS MODERATE FUND",
    "ARTB - PUBLIC INDEX FUND (DIST. ACC)",
    "ARTB-PUBLIC GROWTH FUND DIST. A/C",
    "ARTB PB BALANCED FUND - DIVIDEN",
    "ARTB-PB GROWTH FUND DIST A/C",
    "ARTB-PB CAPITAL PROTECTED DRAGON FUND",
    "ARTB-PUBLIC CHINA TITANS FUND",
    "ARTB-PUBLIC CAPITAL PROTECTED SELECT",
    "ARTB-PB CAPITAL PROTECTED RESOURCES FUND",
    "AMANAHRAYA TRUSTEES BERHAD-PBB MTN",
)
