for refernece

/* FCYCA FCYFD */
DATA FCYCA FCYFD;
   	SET DP_FCY.FCY&REPTMON&NOWK&REPTYY 
        IDP_FCY.IFCY&REPTMON&NOWK&REPTYY;

	CURBAL=CURBALRM;
   	IF CUSTCODE IN (77,78,95,96);

   	IF 3000000000<=ACCTNO<=3999999999 THEN OUTPUT FCYCA;
   	ELSE 								   OUTPUT FCYFD; 

	KEEP ACCTNO CURBAL USER3 PRODUCT;
RUN;
